### ISSUE TITLE
why zgrab send data add tls only get headers 

### ISSUE THREAD

**Issue by alibaba7788** [zmap/zgrab#101]
echo 221.232.66.106 | ./zgrab --port 8443 --tls  --data=./http-req

**Comment by dadrian** [comment]
You should use `--http='\'` instead of `--data='./http-req'`. Our documentation is out of date.

**Comment by chjuheng** [comment]
Why --data http-req only get http headers??

**Comment by alibaba7788** [comment]
but, why --data only get headers?

**Comment by dadrian** [comment]
`--data` only reads a small number of bytes in a single call to read. This likely happened to correspond with the server sending headers.
