### ISSUE TITLE
Refactor Needed

### ISSUE THREAD

**Issue by zakird** [zmap/zgrab#102]
I think we all recognize that the ZGrab code base is a total mess. I'm opening this issue to write down ideas about how we should fix it up.

**Comment by zakird** [comment]
We need to handle multiple connections per host in a generic manner. Users can specify multiple handshakes using a configuration file (probably JSON). If CLI flags are used, then only one scan. Otherwise, we'll allow naming and output them in JSON with something other than "data". Longterm this means that non scan configuration data should be global.

**Comment by zakird** [comment]
Adding a protocol should only require editing one file and defining a well formed function/class/whatever such that it's obvious how to implement new protocols.

**Comment by paul-pearce** [comment]
Adding to zakir's note about adding protocols: It should not only require adding one file but it probably should not then involve a top level flag. e.g. rather than zgrab --newstuff it would probably be zgrab --module=newstuff. This would help with the config file quite a bit.

**Comment by paul-pearce** [comment]
General zgrab options (e.g. --interface) should be separate from protocol specific stuff (e.g. --ftp, --http-max-redirects)

**Comment by zzma** [comment]
Agree, and we should also have a default port for each protocol and not need to specify it from the command line

**Comment by zakird** [comment]
Actually what I'd like is 

zgrab telnet --blah

**Comment by paul-pearce** [comment]
The dependency on dadrian/rc2 should go away.

**Comment by zakird** [comment]
Paul: I'd make that a standalone issue. That's more of a bug than a
refactoring consideration.

**Comment by dadrian** [comment]
I agree with @zakird the interface should look like git (`zgrab protocol --flags`). The golang standard library argument parser supports this.

**Comment by dadrian** [comment]
I'm not convinced that the name in the grab output should be user configurable. We've experienced several times that having overly dynamic JSON output to be very difficult to handle in strongly-typed languages, including in Go itself. As soon as we can't describe the JSON output at compile-time as a struct with optional fields, then dealing with the JSON becomes *incredibly* difficult, especially when trying to deserialize with golang.

**Comment by zakird** [comment]
No, it doesn't. In the case that you're running multiple handshakes, you _must_ name them something. Either you assign an arbitrary name or you let teh user choose. Either way, it's going to be runtime dependent.

**Comment by dadrian** [comment]
@zakird No what doesn't?

Also, why not just use an array? That bypasses the naming issue and is trivially serializable and deserializable.

**Comment by zakird** [comment]
Because you should NEVER have arrays unless you MUST. In order words, if there are records with unknown number of objects. Arrays in _every_ database are entirely unusable and should be avoided at all costs. I would 100% reschema over use arrays in every case. Remember when we had arrays last time and we had to effectively throw away all of our data?

**Comment by dadrian** [comment]
This time, the array would be the same type. Previously, it was not. This enables repeated fields in BigQuery. As for Postgres, we don't actually use Postgres.

However, it turns out the new typing also enables us to do http://stackoverflow.com/questions/18412126/golang-parse-a-json-with-dynamic-key, so I guess the point is moot and we can name the different handshakes. Carry on.

**Comment by zakird** [comment]
It doesn't matter if it's the same type. Analysis is still made infinitely more difficult. I'm 100% against putting an array here (like to the point that I would fork the project level commitment because all the data would be pretty worthless). And while _you_ might not use postgres, others of us do at times.

**Comment by dadrian** [comment]
Well, the good news is we're now in agreement, so we can stop yelling at each other.

**Comment by zakird** [comment]
Configuration and Results should be completely independent of connections. A scanner should be able to decide how many connections they want and should probably just dial themselves.

**Comment by dadrian** [comment]
> A connection should have no metadata attached to it

Can you clarify what you mean here? I'm not sure I follow.

**Comment by zakird** [comment]
Right now, everything is set on the Conn object. This should be set on some sort of higher level configuration object.

**Comment by dadrian** [comment]
Agreed. The Conn object abstraction was incorrect, I think. It was better than what we previously had, but didn't work nearly as well in practice. We should totally scrap that approach and only use the golang net.Conn (and where appropriate, e.g. TLS, SSH), but it shouldn't be the driving abstraction of ZGrab.

**Comment by dadrian** [comment]
Tagging @aaspring since he probably has thoughts on ZGrab after implementing a few TLS things.

**Comment by aaspring** [comment]
Things I think are weird/wrong --
1) The abstraction for cmd flags is broken. You have to set a flag to set a flag to set a flag when then can be checked. No need in having 3 layers.
2) We shouldn't be creating our own structs to JSONize. We should be adding JSON tags to the stdlib structs and then JSONizing straight from them.
3) The entire command line call should be included in the metadata output. Otherwise you can't determine whether a host doesn't have feature X because it doesn't supported it or you didn't supply the cmd-line flag to offer it.

**Comment by zakird** [comment]
We need to have a more consistent interface between ZGrab and ZTag. Right now, it's nearly impossible to know what ztag configuration matches up with various ZGrab configurations. When we name things, the names should match such that it's obvious how to connect the two together.

**Comment by zakird** [comment]
Closing, since this has been handled in ZGrab 2.0.
