### ISSUE TITLE
ZGrab incorrectly outputs TLS Session Ticket support as false

### ISSUE THREAD

**Issue by zakird** [zmap/zgrab#117]
If we do not offer TLS Session Ticket support, we output that the server does not support the extensions, which is not strictly correct. We should not output this, or output it as _null_ , if we haven't tested for it. This has bitten us in the past for other fields.

**Comment by aaspring** [comment]
Identical behavior is present in ```extended_master_secret``` output field and should be fixed in the same PR. Attaching to this Issue IOT for tracking.

**Comment by zakird** [comment]
@dadrian, can you take a look at this when you have a moment?
