### ISSUE TITLE
something go wrong。。。

### ISSUE THREAD

**Issue by kevien** [zmap/zgrab#125]
$ go get github.com/zmap/zgrab
# github.com/zmap/zgrab/ztools/http
ztools/http/request.go:65: request.URL.RawPath undefined (type *url.URL has no field or method RawPath)

**Comment by zlx** [comment]
me too

Have you resolve it now?

**Comment by zlx** [comment]
It seem it dependent go 1.5 https://golang.org/src/net/url/url.go?s=8162:8553#L299

**Comment by zakird** [comment]
Did this resolve your issues?

**Comment by zakird** [comment]
Closing due to lack of response.
