### ISSUE TITLE
example of zgrab

### ISSUE THREAD

**Issue by s3c1t** [zmap/zgrab#129]
i want more description from zgrab all options
or more examples from zgrab options usage
for example: -udp option and etc
please
thanks

**Comment by dadrian** [comment]
Can you provide a bit more information about what you're trying to accomplish with zgrab?

**Comment by s3c1t** [comment]
I had done. banner grabbed some udp ports just with zmap
now this is my question: how to banner grabbing udp ports with -udp option from zgrab
is it ture following similar?
zmap -M udp -p 137 -B 10M x.x.x.x/24  -o - |./zgrab -port 137 -udp -output-file banner-netbios.json

**Comment by zakird** [comment]
Closing since this is improved in ZGrab2, which is superseding this project.
