### ISSUE TITLE
Need more examples about zgrab and ztag

### ISSUE THREAD

**Issue by jszhujun2010** [zmap/zgrab#132]
Hi!
I have tried to scan different ports, but seemed to succeed only in (443, https, tls), the example in readme file.

For example, I want to scan port 80 and I use the following command:

``` sh
zmap --config=/root/zmap.conf -p 80 --output-fields=* | ztee results.csv | ./zgrab --port 80 --data=./http-req | tee banner.json | ztag -p 80 -P http -S get -l mylog > final.json
```

I get nothing in file final.json and many errors occurred in my console(like i/o timeout or EOF). My confusion is that what is the correct parameter to specify in zgrab and ztag so that I can parse useful information.
Not only heartbleed, can you show more other detailed examples to combine zgrab and ztag(I'm confused about about the programs' help options too...).

**Comment by xtalentfeng** [comment]
replace “./zgrab --port 80 --data=./http-req”  with   "./zgrab_ --port 80 --http="/"".

**Comment by dadrian** [comment]
I updated the HTTP example in README.md
