### ISSUE TITLE
Parse type of ECDSA key and full key itself  (not components)

### ISSUE THREAD

**Issue by zakird** [zmap/zgrab#136]
e.g.,

        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub: 
                    04:ca:fb:a9:62:b8:2d:ad:cb:62:8a:0b:cc:e3:5c:
                    32:d7:bd:dd:82:17:d8:1e:04:5d:41:7a:ef:4b:eb:
                    0c:fe:1e:a0:70:07:fc:51:b3:75:c3:c5:60:96:af:
                    2e:7c:1b:cd:db:56:dd:71:e4:51:56:f1:b8:da:0f:
                    10:d8:87:3b:1c
                ASN1 OID: prime256v1

**Comment by shoegaze** [comment]
Okay, so I think I'm done with this. I haven't touched anything that outputs though, so I'm unsure if it will show up formatted correctly, if at all. Is that all handled, or do I need to change that as well?

**Comment by zakird** [comment]
What is the output now?

**Comment by shoegaze** [comment]
I don't actually know. How can I see what was being output before? I know this stuff shows up in Censys, but...

**Comment by zakird** [comment]
I thinik we're fine with just the new one

**Comment by shoegaze** [comment]
Okay, but I'm not sure where to look at the output. Like is it all handled dynamically or am I going to have to change some configuration somewhere to include the raw key data as it gets output?

**Comment by zakird** [comment]
You probably need to include it in x509/json.go

**Comment by shoegaze** [comment]
Ah, that's what I was looking for.
