### ISSUE TITLE
Parse SKID and AKID consistently

### ISSUE THREAD

**Issue by zakird** [zmap/zgrab#138]

**Comment by zakird** [comment]
I suspect b64 is the right way to go

**Comment by dadrian** [comment]
We should match whatever we're using for fingerprints.

**Comment by zakird** [comment]
So hex?

**Comment by dadrian** [comment]
Yes. That also makes it easier to search in ES.

**Comment by zakird** [comment]
In what sense?

**Comment by dadrian** [comment]
Position-independent encoding, since log(16) divides 8, and log(64) does not divide 8. So any byte-aligned substring will always be encoded the same, regardless of where within the string it is. Also, ES doesn't treat it as binary as default, which means it's actually searchable.

**Comment by zakird** [comment]
@dadrian the second part is just dependent on how we index it.

**Comment by zakird** [comment]
fixed 7f9dbe5
