### ISSUE TITLE
Add names field

### ISSUE THREAD

**Issue by zakird** [zmap/zgrab#140]
collect all names that the certificate is valid for and put them in one place

**Comment by zzma** [comment]
Since we're adding the `--lookup-domain` functionality (https://github.com/zmap/zgrab/pull/127), do we want to provide a "matches_domain" field here? Or leave it up to the user to check domain vs names?

**Comment by zakird** [comment]
Yes, but that won't go in certificate itself, but rather the TLS handshake (where it is currently)

**Comment by shoegaze** [comment]
Just fixed some merge issues. This should be good to go now.
