### ISSUE TITLE
Add SHA256(SPKI + Subject)

### ISSUE THREAD

**Issue by zakird** [zmap/zgrab#141]
Add field that uniquely identifies a CA.

Unclear what to name this. @dadrian ideas?

**Comment by dadrian** [comment]
`subject_key_fingerprint`? Someone else on the Internet must have had this problem. Also, what does this really gain us vs just using the SHA256 fingerprint. Are there CA's with multiple certs that have identical subjects and keys, but different other fields? What fields are they changing? Why do we need this?

**Comment by zakird** [comment]
Yes, almost every CA operates like that.

**Comment by dadrian** [comment]
We can't be the only people who have wanted an identifier like this. What does crt.sh do?

**Comment by zakird** [comment]
This. That's how I realized it was useful ;)
