### ISSUE TITLE
Add SHA256(TBSCertificate No Poison)

### ISSUE THREAD

**Issue by zakird** [zmap/zgrab#143]

**Comment by dadrian** [comment]
No poison? Does this have something to do with name redaction?

**Comment by zakird** [comment]
CT Poison.

**Comment by shoegaze** [comment]
Ref here: http://www.alvestrand.no/objectid/submissions/1.3.6.1.4.1.11129.2.4.3.html

**Comment by shoegaze** [comment]
opened https://github.com/zmap/zgrab/tree/NoPoisonFingerprint to solve this, will submit pr shortly.

**Comment by shoegaze** [comment]
Fixed by #179
