### ISSUE TITLE
Add support for validation against multiple root stores

### ISSUE THREAD

**Issue by zakird** [zmap/zgrab#145]
Unclear whether we should do this explicitly or not. @dadrian thoughts?

We'll want to for sure add support for Apple, Microsoft, NSS, and likely 2--3 others (e.g., Google CT, Android, and Java)

**Comment by dadrian** [comment]
I don't want to have to keep track of all the different root stores as part of the ZGrab binary. Maybe add the ability to have multiple root stores, and then the ability to name/tag the multiple roots as Apple/MS/NSS/MyFavoriteRoot?

**Comment by zakird** [comment]
That's fine with me. How do we handle on the CLI? and then do we move them all to the right place in ZTag?

**Comment by dadrian** [comment]
Ideally the "naming" of the roots would prevent having to do a bunch of manipulation in ZTag.

**Comment by dadrian** [comment]
I'm not sure how you expose this on the CLI though.

**Comment by zakird** [comment]
Well it goes into the protobuf, so there will necessarily have to be manipulation there. :|
