### ISSUE TITLE
Add searchable names field

### ISSUE THREAD

**Issue by zakird** [zmap/zgrab#146]
Elasticsearch is terrible at handling `*name` searches, e.g. `*.github.com`. For each certificate, parse out the name tree. For example, a certificate that's valid for a.b.domain.com and c.domain.com would have

 - a.b.domain.com
 - b.domain.com
 - c.domain.com
 - domain.com
 - com

**Comment by dadrian** [comment]
Shouldn't we change this by changing the Elasticsearch field processor (or whatever it's called) that we use on CN and SAN?

**Comment by zakird** [comment]
If we do that we should likely just do it in esloader? It's pretty painful to write ES indexers. The reason I originally put here is because we'll also need this for CT monitoring and idk how many places we want to do it.

**Comment by dadrian** [comment]
Well, we should definitely do #140. I'm not convinced this should go in ZGrab though.

**Comment by zakird** [comment]
Yeah, I don't disagree. My original plan was to just add it in ZTag. However, that's not a great solution because ctsync doesn't go through ZTag, it goes directly from ZGrab. No matter what, it seems really ugly. :|

**Comment by zakird** [comment]
I guess one question is whether we ever need this in ZDb.

**Comment by dadrian** [comment]
Well, long term ZTag will go away, and then it can probably just be imported as needed from CTsync or some other library (assuming CTsync is also in golang).

**Comment by zakird** [comment]
It is. I agree 100% that this doesn't belong in ZGrab. I just don't like any solution. :|

**Comment by dadrian** [comment]
Yeah. But given #140, it's pretty easy to implement anywhere.

**Comment by zakird** [comment]
Yeah that's fine. So we'll just do it in CTSync and ZTag for now?

**Comment by dadrian** [comment]
SGTM.
