### ISSUE TITLE
Certificate Policy Qualifiers

### ISSUE THREAD

**Issue by zzma** [zmap/zgrab#160]
Parse out certificate policy qualifiers (RFC 5280 - 4.2.1.4. Certificate Policies):
1. CPS (Certification Practice Statement) URI
2. UserNotice

**Comment by kumarde** [comment]
@zhengping12 has already parsed out UserNotice for some zlint work, I'll handle the CPS URI parsing.

**Comment by zakird** [comment]
@kumarde what is the status of this? We want to have this done before we run anything for ZLint?

**Comment by zakird** [comment]
@justinbastress has confirmed that we output both of these fields these days. Closing.
