### ISSUE TITLE
names field doesn't capture redacted names

### ISSUE THREAD

**Issue by zakird** [zmap/zgrab#171]
Because ?.domain.com isn't technically a valid name, this won't end up being put into the `names` array. We should make our domain validator less strict to accept these. The names field is already a custom construct and given that we want to support easily searching for certificates, it makes the most sense to just include these.

**Comment by shoegaze** [comment]
This is approximately how I think this will work: 

`			flag := true
 
 			if name[0] == '?' {
				flag = govalidator.IsURL(name[2:])
			} else {
 				flag = govalidator.IsURL(name)
 			}
 
 			// Check that this is actually a url and not something else
 			if flag {
 				jc.Names = append(jc.Names, name)
 			}`

**Comment by zakird** [comment]
Oh man. I don't actually know how redaction works. Am I allowed to do `x.?.y.z`?

**Comment by shoegaze** [comment]
I have no idea. I'm sure there's a `string.contains('?')` we could use.

**Comment by zakird** [comment]
@dadrian do you know the policy here?

**Comment by umbernhard** [comment]
FWIW, I think '?' is not allowed in any domain, so we should never see one a.?.b. Gonna actually fix this problem now.
