### ISSUE TITLE
[ERROR] banner-grab: Conversation error with remote host

### ISSUE THREAD

**Issue by Achelics** [zmap/zgrab#176]
---
- I had met a question: I grabed the http protocol's banners, and I got this information. </p>
  [ERROR] banner-grab: Conversation error with remote host 192.168.12.207:80: read tcp 192.168.12.39:51512->192.168.12.207:80: i/o timeout</p>
- My ip address is 192.168.12.39, but the remote address was openinge http service in 80 port. How can I avoid that? thx! # #

**Comment by zakird** [comment]
Can you provide the command you are running?
