### ISSUE TITLE
names field is not deduplicated

### ISSUE THREAD

**Issue by zakird** [zmap/zgrab#178]
The values of the `names` field in certificates are not currently de-duplicated. Given that many certificates have values in both the CN and subject alternate name, most certificates have values like `www.censys.io, www.censys.io, censys.io`.

**Comment by shoegaze** [comment]
There isn't a canonical way to deduplicate slices. I could either maintain a map alongside the slice of names to check whether or not I've seen the slice before, or I could linearly search the slice every time to check for repeats. I think I'm gonna use the map approach and see how it works.

**Comment by shoegaze** [comment]
Actually, digging through the code, does https://github.com/zmap/zgrab/blob/master/ztools/x509/json.go#L277 not do it?

**Comment by shoegaze** [comment]
Am I just looking at the wrong thing?

**Comment by zakird** [comment]
It doesn't appear so. What I copied is what was output

**Comment by shoegaze** [comment]
I think I might punt this to @mhyder13 to see if he can figure it out. The dedup'ing code looks correct to me, unless there's like pointer magic going on.

**Comment by zakird** [comment]
@shoegaze is that dedup for the field in the SAN extension, or the `names` field that combines all of them?

**Comment by zakird** [comment]
I just looked and it is for the right field. Did this just get added recently? Maybe this certificate was parsed before then? I'll manually parse it and see if the issue still persists.

**Comment by zakird** [comment]
This looks fixed now. This must have been parsed with an old version.
