### ISSUE TITLE
HTTP Memory Leak

### ISSUE THREAD

**Issue by zakird** [zmap/zgrab#187]
It looks like ZGrab leaks memory when performing HTTP scans. This is bad enough that it leaks enough memory that it is OOM killed on a 16GB machine before an IPv4 scan can be completed. 

The last successful scan we had was on September 5th, so it may be that the recent port following changes were what caused this.

**Comment by micgob** [comment]
HI,
Any workarounds?

**Comment by mawenlong3** [comment]
ZGrab has also the problem with  leaks memory when performing HTTP scans. I used the command like this 
`zmap -p 80 -o - -B 30M -l 80-http-ipv4_full-20170426T1630-zmap-log.log -m 80-http-ipv4_full-20170426T1630-zmap-metadata.json| ztee 80-http-ipv4_full-20170426T1630-zmap-results.csv | zgrab --port=80 --http="/"  --timeout=5 --senders=2000  --http-max-redirects=2 --output-file=80-http-ipv4_full-20170426T1630-zgrab-results.json --metadata-file=80-http-ipv4_full-20170426T1630-zgrab-metadata.json --log-file=80-http-ipv4_full-20170426T1630-zgrab-log.log`
some hours later,I get the error ‘Apr 27 09:11:59.386 [FATAL] ztee: Error writing to stdout’
