### ISSUE TITLE
in HTTP mode, zgrab doesn't output TLS session info if there's an error after a TLS session is successfully established

### ISSUE THREAD

**Issue by billmarczak** [zmap/zgrab#190]
Here's my command, where xxx.xxx.xxx.xxx is some IP:

`echo "xxx.xxx.xxx.xxx" | ./zgrab --port 443 --tls --http="/"`

The IP xxx.xxx.xxx.xxx has the following property: I can successfully establish a TLS connection on port 443, but whenever I send an HTTP GET request, the server closes the connection without returning any data.  Unfortunately, all zgrab gives me is:

`{"ip":"xxx.xxx.xxx.xxx","timestamp":"[some-timestamp]","data":{"http":{}},"error":"Get https://xxx.xxx.xxx.xxx:443/: unexpected EOF"}`

In addition to that error, I feel like it should also give me the details of the TLS session that was successfully established (e.g., certificate, blah blah).  Basically, I want to be able to scan the Internet once on port 443, and get (a) TLS certificates for every host on 443 that supports TLS, and (b) the response (or error) to an HTTP GET request.

**Comment by zzma** [comment]
Bill - is there a specific IP address that you are observing this behavior on? It would be helpful to have a concrete example.

**Comment by billmarczak** [comment]
Sure, take this one as an example: `52.50.169.99`

**Comment by billmarczak** [comment]
We can successfully establish a TLS session with this IP:

`openssl s_client -connect 52.50.169.99:443`

Yet zgrab doesn't return any TLS details about it in the output while in HTTP mode:

`echo "52.50.169.99" | ./zgrab --port 443 --tls --http="/"`

yields:

`{"ip":"52.50.169.99","timestamp":"2016-10-05T23:30:24Z","data":{"http":{}},"error":"Get https://52.50.169.99:443/: unexpected EOF"}`

**Comment by zzma** [comment]
Thanks for the example, Bill. I am able to recreate the issue. I'll take a deeper look at the issue tomorrow.

**Comment by zakird** [comment]
This should be resolved by #192. @billmarczak can you please confirm this meets your needs?

**Comment by billmarczak** [comment]
Yes it does!  Thanks @zzma and @zakird, you guys are the best :)

**Comment by zakird** [comment]
yay! it's all @zzma .
