### ISSUE TITLE
bug at ztools/util line84

### ISSUE THREAD

**Issue by DivineRapier** [zmap/zgrab#199]
![bug](https://cloud.githubusercontent.com/assets/21213088/20332966/718af184-abea-11e6-92e5-385b39122c81.png)

when set maxReadLen to 8192 or times of 8192, it may be not working any more

**Comment by DivineRapier** [comment]
i think just add 
``` go
if appendBytesLen == 0 {
    appendBytesLen = READ_BUFFER_LEN
}
```
below line 84

**Comment by dadrian** [comment]
Fixed.
