### ISSUE TITLE
Not collecting entire HTTP banner 

### ISSUE THREAD

**Issue by beruhan** [zmap/zgrab#204]
today I used zgrab to grab http banner,but I most of the data I got has uncomplete response.how to dealwith this case？ I install zgrab use the command 
```
go get github.com/zmap/zgrab
cd $GOPATH/src/github.com/zmap/zgrab
go   
```
@corny @jhalderm @zakird @ppannuto @ewust

**Comment by zakird** [comment]
You can control how much data is returned by setting --http-max-size. Please do not tag individual contributors in the future.
