### ISSUE TITLE
Zgrab gets hooked in an infinite web page download. Should not

### ISSUE THREAD

**Issue by eldraco** [zmap/zgrab#208]
If you use this honeypot https://github.com/eldraco/theinfinitewebpage, Zgrab will get hooked for a long time (1hs so far) and download a lot of data (90G so far) without cutting the connection. 
Most webcrawlers do not.

**Comment by dadrian** [comment]
Hi @eldraco.

What command line flags were you using?

**Comment by eldraco** [comment]
Sorry but I didn't run Zgrab. I actually run the honeypot and somebody used Zgrab to scan us. Unfortunately for him he got hook for 1hs. 
So I can not tell you how to reproduce it.
They were requesting with the useragent "Mozilla/5.0 zgrab/0.x" if it helps.

**Comment by dadrian** [comment]
Do you by chance have the IP of that useragent? Are you willing to share if it was in the 141.212.0.0/16 subnet?

**Comment by ajholland** [comment]
Looked into this. Zgrab will automatically time out after 10s and only store up to 256 kb.

**Comment by dadrian** [comment]
@ajholland thanks for looking into this!

@eldraco It looks like the default settings prevent the infinite download. Someone must have configured ZGrab dangerously, or be lying about their useragent. Thanks for heads up, anyway. Still good to validate we behave sanely.
