### ISSUE TITLE
ztls: CHACHA20_POLY1305 ciphersuites ids

### ISSUE THREAD

**Issue by SergeyFrolov** [zmap/zgrab#213]
According to [rfc7905](https://tools.ietf.org/html/rfc7905) following cipher suites are defined as:
   TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256   = {0xCC, 0xA8}
   TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 = {0xCC, 0xA9}
   TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256     = {0xCC, 0xAA}

   TLS_PSK_WITH_CHACHA20_POLY1305_SHA256         = {0xCC, 0xAB}
   TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256   = {0xCC, 0xAC}
   TLS_DHE_PSK_WITH_CHACHA20_POLY1305_SHA256     = {0xCC, 0xAD}
   TLS_RSA_PSK_WITH_CHACHA20_POLY1305_SHA256     = {0xCC, 0xAE}

ztls appears to have different ids for them:
https://github.com/zmap/zgrab/blob/ae5ee0978edafc7ba8d3da48acfaa2c003cb890c/ztools/ztls/cipher_suites.go#L793-L795

**Comment by SergeyFrolov** [comment]
The values in RFC are formally assigned, and ones currently in ztls are the old values.
Currently Chrome sends both old and new values for some ciphersuites, so it might be a good idea to keep the old values with "_OLD" suffix.
I can send a PR, when we figure out the details.
Thanks

**Comment by zakird** [comment]
This sounds fine to me.

**Comment by dadrian** [comment]
Agreed.
