### ISSUE TITLE
Breakout xssh dh_key_exchange parameters

### ISSUE THREAD

**Issue by aaspring** [zmap/zgrab#218]
Currently, all DH parameters are outputted under data->xssh->dh_key_exchange->parameters. Move these so that they are sub-grouped under parameters based on the exchange type (DH, ECDH, etc). The output should be similar to how the different host keys are sub-grouped under data->xssh->dh_key_exchange->server_host_key.

**Comment by cdzombak** [comment]
Does https://github.com/zmap/zgrab/pull/286 (merged in July) resolve this?

**Comment by dadrian** [comment]
Yes.
