### ISSUE TITLE
Figure out if `--force-ciphers` can be removed

### ISSUE THREAD

**Issue by dadrian** [zmap/zgrab#236]
We originally had this flag so that we could send export ciphers and get a certificate, even though we didn't actually speak them. Nowadays, we speak a lot more ciphers, so we probably don't need this flag anymore.

We should check to see what ciphers we do speak, relative to what we don't. There's a list somewhere (I think there's a cipher_names.go file). We should figure out what ciphers we'd "lose" if we removed this option, and then make a decision.

The goal would be to remove the logic around `--force-ciphers`, since it's complicated and annoying to maintain.

**Comment by ajholland** [comment]
cipher_suites.go has two arrays, stdlibCipherSuites and implementedCipherSuites, I combined these and diffed them with the list of possible cipher suite ID's to come up with the following list of 289 unsupported cipher suites:
 
[unsupported.txt](https://github.com/zmap/zgrab/files/800340/unsupported.txt)

**Comment by zakird** [comment]
Given that there are _many_ other ciphers that we might one day need to test for, I think this should remain for now.
