### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by denniskai1234** [zmap/zgrab#24]
Hey.

I think im just too retarded for the install so i need help.

ls  $GOPATH
src
root@install:~# ls  $GOPATH/src
zgrab  ztools

Should be correct or?

Then i went in the zgrab folder and did the go build this was what i got from it:

go build
main.go:13:2: import "github.com/zmap/zgrab/zlib": cannot find package
main.go:14:2: import "github.com/zmap/ztools/processing": cannot find package
main.go:15:2: import "github.com/zmap/ztools/zlog": cannot find package
main.go:16:2: import "github.com/zmap/ztools/ztls": cannot find package

So i changed the urls to the working ones:

	"github.com/zmap/zgrab/tree/master/zlib"
	"github.com/zmap/ztools/tree/master/processing"
	"github.com/zmap/ztools/tree/master/zlog"
	"github.com/zmap/ztools/tree/master/ztls"

again go build now i get this:

go build
can't load package: package .:
main.go:1:14: expected ';', found 'import'

Hope to get a tutorial how to install this correctly... thanks!

**Comment by dadrian** [comment]
Try clearing out zgrab and ztools from your $GOPATH, and then just run:

`go get github.com/zmap/zgrab`

**Comment by denniskai1234** [comment]
go get github.com/zmap/zgrab
# cd .; git clone https://github.com/zmap/zgrab /root/go/src/github.com/zmap/zgrab
package github.com/zmap/zgrab: exec: "git": executable file not found in $PATH

**Comment by dadrian** [comment]
Do you have git installed?

**Comment by denniskai1234** [comment]
After installing git:

go get github.com/zmap/zgrab
# github.com/zmap/ztools/ztls
src/github.com/zmap/ztools/ztls/cipher_suites.go:66: undefined: cipher.AEAD
src/github.com/zmap/ztools/ztls/cipher_suites.go:133: undefined: cipher.AEAD
src/github.com/zmap/ztools/ztls/cipher_suites.go:149: undefined: cipher.AEAD
src/github.com/zmap/ztools/ztls/handshake_server.go:560: undefined: crypto.PublicKey
src/github.com/zmap/ztools/ztls/tls.go:93: undefined: net.Dialer

**Comment by dadrian** [comment]
What version of Go do you have installed? It needs to be at least 1.3.3.

**Comment by denniskai1234** [comment]
updated to ./go version
warning: GOPATH set to GOROOT (/root/go) has no effect
go version go1.4 linux/amd64

go get github.com/zmap/zgrab
# github.com/zmap/zgrab/zlib
../src/github.com/zmap/zgrab/zlib/config.go:4: import /root/go/pkg/linux_amd64/crypto/x509.a: not a package file

**Comment by dadrian** [comment]
It looks like something is still misconfigured with your Go environment. You'll want to make $GOPATH somewhere different than wherever you install the go binary to.

Try following these instructions (http://golang.org/doc/code.html) on how to set up a golang environment. Once that is set up, try running go get github.com/zmap/zgrab again.

**Comment by denniskai1234** [comment]
Okay its installed now, how can i scan now lets say the whole world for website titels and get them into a file?

And thanks again for the super fast help!

**Comment by dadrian** [comment]
@denniskai1234, see my answer here https://github.com/zmap/zmap/issues/233, which describes a similar process. You'd want to grep for `<title>` instead.
