### ISSUE TITLE
Runtime error in logger

### ISSUE THREAD

**Issue by tfrommen** [zmap/zgrab#262]
Hi there,

I just built zgrab; no problem.  
When I tried to run `zgrab --help`, however, I was presented with this:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x749c19]

goroutine 1 [running]:
github.com/zmap/zgrab/ztools/zlog.New(0xbbb1c0, 0xc04205c010, 0x8e3ecd, 0x3, 0x14)
        /Users/tfrommen/go/src/github.com/zmap/zgrab/ztools/zlog/logger.go:100 +0x169
github.com/zmap/zgrab/ztools/zlog.init()
        /Users/tfrommen/go/src/github.com/zmap/zgrab/ztools/zlog/logger.go:77 +0x21b
github.com/zmap/zgrab/zlib.init()
        /Users/tfrommen/go/src/github.com/zmap/zgrab/zlib/zgrab.go:110 +0x70
main.init()
        /Users/tfrommen/go/src/github.com/zmap/zgrab/summary.go:111 +0x86
```

I had a look at the [logger](https://github.com/zmap/zgrab/blob/5cee42af64e54ae486e9ad48cd05d294dbe296b4/ztools/zlog/logger.go), and it turned out my file `stats` was `nil`- don't ask me for a reason, I'm fairly new to Go and all this.

Integrating a simple check for (not) `nil` solved the issue, like so:

```go
func New(out io.Writer, prefix string) *Logger {
	useColor := false
	file, ok := out.(*os.File)
	if ok {
		stats, _ := file.Stat()
		// Check to see if output is a terminal
		if stats != nil && (stats.Mode() & os.ModeCharDevice) != 0 {  // <----
			useColor = true
		}
	}
	logger := Logger{
		out:      out,
		prefix:   prefix,
		useColor: useColor,
	}
	return &logger
}
```

I'd be happy to send a PR, if you want.

**Comment by zakird** [comment]
Is this in master? I'm unable to produce this problem offhand.

**Comment by tfrommen** [comment]
@zakird yes. I ran `$ go get github.com/zmap/zgrab`, so in the end I cloned the `master` branch. I also checked and verified in GOPATH.

I am running Go 1.8 for Windows, 64-bit, on Windows 7. Anything else I can provide you with?

**Comment by tfrommen** [comment]
Hm, I just cloned the repo to some temp folder (directly via `$ git clone git@github.com:zmap/zgrab.git`), and building and executing it works just fine.

Inside GOPATH (i.e., `/Users/tfrommen/go/src/github.com/zmap/zgrab`) I can build it, but get the error when trying to execute... 🤔

**Comment by dadrian** [comment]
Interestingly, I can't reproduce this on OS X, but am instead experiencing an entirely different crash when running `--help`. I suspect this issue is Windows specific. I'm happy to merge that check, but I'm not sure the rest of ZGrab works on Windows. I'm fairly certain our X.509 library panics() if you attempt to call Verify on Windows.
