### ISSUE TITLE
How should I use --lookup-domain flag?

### ISSUE THREAD

**Issue by wx-Yao** [zmap/zgrab#264]
Basically, I'm not that familiar with Go and I couldn't fix this on my own.

I use this command to grab something: 

` echo "www.baidu.com" | zgrab --port 80 --data http-req-domain --lookup-domain | jq '.' `

return json (summary part omitted) :

`Mar 30 11:52:03.966 [ERROR] banner-grab: Could not connect to www.baidu.com remote host <nil>: dial tcp: lookup <nil>: no such host
{
   "ip": "<nil>",
  "domain": "www.baidu.com",
  "timestamp": "2017-03-30T11:52:03+08:00",
  "data": {},
  "error": "dial tcp: lookup <nil>: no such host",
  "error_component": "connect"
}
...
`
and I've tried other combination of options, it still doesn't work. Can someone show me how to use this functionality? much appreciate!

**Comment by zzma** [comment]
You need to specify the HTTP endpoint that you want to access (i.e. make a GET request for). Try this:

`echo "www.baidu.com" | zgrab --port 80 --http / --lookup-domain` 

If you want to follow HTTP redirects, you can specify the `--http-max-redirects` flag. Hope this helps.

**Comment by wx-Yao** [comment]
@zzma 
sorry to bother you again XD. 

When I test one domain, it works fine. Test 50 domains, it works fine as well. But there was something wrong with the result when I needed to grab 2700+ domains. The error log said "too many open files" and the return json had many nulls. I google that key words and guess that was due to too many connections at the same time. Should I use proxy or .. how could I fix that ?

**Comment by zzma** [comment]
You probably have too many open files, and need to increase the number file descriptors your process can use. I'd start by looking at ulimit. If you google that error, there's a lot of documentation out there on changing this limit. Check this out: http://stackoverflow.com/questions/32325343/go-tcp-too-many-open-files-debug

**Comment by manuelbua** [comment]
I have the same problem and `ulimit` won't solve that in my case, still wondering what's up:
```
open files                      (-n) 512000
```

I can see the default behavior for `HTTP/1.1` is to persist connections (keep-alive), and since i'd like to try specifying a "Connection: close" header in the request i'm now diving into the sources, any pointers?

**Comment by manuelbua** [comment]
For other that may incur in the same problem, i'm working it around by doing the following:
```
echo 'x.y.z.w,a.b.c.d.e' | zgrab -port 443 -tls -data <(echo -e "GET / HTTP/1.1\r\nHost: %d\r\nConnection: close\r\nUser-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36\r\n\r\n") --output-file=banners-443.json
```

This works perfectly fine for my use-case, but ymmv!
