### ISSUE TITLE
HTTP Scan Memory Leak bug seems Not Fully repaired

### ISSUE THREAD

**Issue by mawenlong3** [zmap/zgrab#266]
I use the latest zgrab to grab http banner,but the zgrab was killed before an IPv4 scan can be completed.The command is  `nohup zmap -p 80 --output-fields=* -b blacklist.conf -B 30M -l 80-http-ipv4_full-20170503T1601-zmap-log.log -m 80-http-ipv4_full-20170503T1601-zmap-metadata.json 2>/dev/null | ztee 80-http-ipv4_full-20170503T1601-zmap-results.csv | zgrab --port=80 --http="/"  --timeout=5 --senders=2000  --output-file=80-http-ipv4_full-20170503T1601-zgrab-results.json --metadata-file=80-http-ipv4_full-20170503T1601-zgrab-metadata.json --log-file=80-http-ipv4_full-20170503T1601-zgrab-log.log 2>/dev/null &`,Any workarounds?

**Comment by Achelics** [comment]
Hi, maybe i know your question, I got your error information in the question HTTP Memory Leak. You said your error information was  **[FATAL] ztee: Error writing to stdout** . The error information we can find in "https://github.com/zmap/zmap/blob/master/src/ztee.c" file. 
</b> In this file, we can find this code:`if (ferror(output_file)) {log_fatal("ztee", "Error writing to output file");}`</b>
It;s obvious, your handle the error and stdout streaming to the stout. you need to divide the error and stdout streaming.

**Comment by mawenlong3** [comment]
Hi,I have  divide the error and stdout streaming use command as flows,`sudo nohup zmap -p 80 --output-fields=* -B 30M -l zmap-log.log -m zmap-metadata.json 2> zmap-error.log | ztee zmap-results.csv 2> ztee-error.log | zgrab --port=80 --http="/" --timeout=5 --senders=1500 --output-file=zgrab-results.json --metadata-file=zgrab-metadata.json --log-file=zgrab-log.log 2> zgrab-error.log` ,but  zgrab was  killed  as before.Is there anyone can help me?

**Comment by Achelics** [comment]
Wow, That;s interesting! I just want to know your zgrab version. And you use the previoue version of zgrab, thsis problem also again?

**Comment by mawenlong3** [comment]
Yes,I have run the different zgrab version I had saved! All of zgrab version have this problem!My  machine memory is 8G,Ubuntu 16.04 LTS!

**Comment by dadrian** [comment]
We have a version of ZGrab that doesn't seem to leak memory on HTTP scans. We're working on fixing it up, and hope to have it merged into master next week.

**Comment by mawenlong3** [comment]
Ok thanks, I'm looking forward to your good news~~

**Comment by mawenlong3** [comment]
I'm testing the zgrab that fixed the memory leak problem, After running for about two hours ,I made the snapshot of my machine memory. I suspect there still be a memory leak!
![123](https://cloud.githubusercontent.com/assets/18480704/26146555/281a461c-3b23-11e7-8d00-f9fb0954726c.png)

**Comment by dadrian** [comment]
We saw asymptotically leveling off memory usage during the course of a full IPv4 scan with the HTTP module. I'm not convinced that's not just an issue with the Go GC. In your snapshot, it looks like ZGrab is using less memory than zmap. Did the memory usage growth continue for you?

**Comment by mawenlong3** [comment]
zmap -u param seems unstable,I use the following command,`zmap -p 80 --output-fields=* -b -B 30M -l zmap-log.log -m zmap-metadata.json -u zmap-status.csv --quiet`, it often occured the error 'could not open output file zmap-status.csv',I need to run many times to succeed.I have used the sudo
