### ISSUE TITLE
build instructions are wrong

### ISSUE THREAD

**Issue by whithajess** [zmap/zgrab#27]
Instructions refer to $GOPATH/src/zgrab and $GOPATH/src/ztools 

#24 uncovered this same problem go build looks for them in the same location as the "go get github.com/zmap/zgrab" command creates them in: 

$GOPATH/src/github.com/zmap/zgrab
$GOPATH/src/github.com/zmap/ztools 

Not to mention the go get command does all this for us.

**Comment by dadrian** [comment]
Yeah, you're right. I thought I had updated the install instructions after #21, but apparently didn't.

**Comment by whithajess** [comment]
Opened a pull requests for both the issues I encountered with the instructions your welcome to close if you wan't to write your own.

**Comment by dadrian** [comment]
Closed by #26
