### ISSUE TITLE
--encoding option not working

### ISSUE THREAD

**Issue by whithajess** [zmap/zgrab#29]
The encoding option gives 3 possible outputs string|hex|base64 with string being default.

It seems string and base64 both give out the same base64 output
and that hex gives out a base64 hex output

**Comment by dadrian** [comment]
We respect this option again, at least for the `--data` flag. You'll want to pull latest master.

**Comment by whithajess** [comment]
Thanks! this is exactly what I needed thought it didn't work originally after `go get -u github.com/zmap/zgrab` but I needed to  `go build` (I'm a go newbie couldn't figure out how to write the patch)

**Comment by whithajess** [comment]
@dadrian are you generally in some irc channels or have some kind of chat that I can contact you over? would be cool if I can ask you some questions without having to raise an issue.
