### ISSUE TITLE
add manpage

### ISSUE THREAD

**Issue by zakird** [zmap/zgrab#3]

**Comment by temal-** [comment]
Hi,
any preferences in the format you want to have the manpage? 

groff?
```
.TH ZGRAB 1 "JAN 2015" "zgrab-git" "User Manuals"
.SH NAME
zgrab \- (TLS) banner grabber
.SH SYNOPSIS
.I zgrab
.B [-banners] [-ca-file
.I file
.B ]
.B [-cbc-only] [-data
.I message
.B ] [-ehlo]
.I domain
.B ] [-encoding
.I encoding
.B ] [-heartbleed] [-imap] [-input-file
.I file
.B ] [-interface
.I interface
.B ] [-log-file
.I file
.B ] [-metadata-file
.I file
.B ] [-modbus] [-output-file
.I file
.B ] [-pop3] [-port
.I port
.B ] [-senders
.I senders
.B ] [-smtp] [-smtp-help] [-starttls] [-timeout
.I timeout
.B ] [-tls] [-tls-version
.I version
.B ] [-udp]
.SH DESCRIPTION
.B zgrab
grabs the banner from an ip provided by stdin or a file ...
```

asciidoc?
```
zgrab(1)
==========

NAME
----
zgrab - (TLS) banner grabber

SYNOPSIS
--------
[verse]
'zgrab' [-banners] [-ca-file file ] [-cbc-only] [-data message ] [-ehlo]
       domain ] [-encoding encoding ] [-heartbleed] [-imap] [-input-file  file
       ]  [-interface  interface  ]  [-log-file  file ] [-metadata-file file ]
       [-modbus] [-output-file file ] [-pop3] [-port port ] [-senders  senders
       ]  [-smtp]  [-smtp-help]  [-starttls] [-timeout timeout ] [-tls] [-tls-
       version version ] [-udp]

DESCRIPTION
-----------
zgrab grabs the banner from an ip provided by stdin or a file ...
```

To compare them, the asciidoc example would need a couple of `*` and `_` ... but since it's only for a short overview, I used the output from the groff example.

Second question: For which other projects (zmap, ztee ..) do you need a manpage?

**Comment by dadrian** [comment]
Personally, I dislike roff, but if you want to write some documentation in it, by all means go for it! In zmap we use ronn, which is a markdown-like language that compiles into roff.

**Comment by dadrian** [comment]
ztee also needs a manpage. However, we're going to be switching to the ztee in the zmap repository and getting rid of the ztee in its standalone repository.

**Comment by temal-** [comment]
I was asking (and showing examples) because I didn't knew which kind of format you guys prefer. Ronn looks quite nice and since it's already used in zmap, I'll give it a try. I'll comment here as soon as I'm done.
