### ISSUE TITLE
IP Resolution on doing a domain lookup

### ISSUE THREAD

**Issue by ishankaru** [zmap/zgrab#306]
When running a command like this:
echo "github.com"  | zgrab  --http="/" -lookup-domain

Is there a way to get the IP to populate instead of showing 'nil', was not certain if this was a bug, how it is or if there was a parameter I can use to resolve the IP.

banner-grab: Could not connect to remote host http://github.com/: Get https://github.com/: stopped after 0 redirects
{**"ip":"\u003cnil\u003e"**,"domain":"github.com"..........

**Comment by zakird** [comment]
Closing as this has been addressed in ZGrab2, which is superseding this project.
