### ISSUE TITLE
0.25 BTC bounty for custom http header

### ISSUE THREAD

**Issue by roger32843948** [zmap/zgrab#307]
I need to insert a custom HTTP header in ZGrab when using --data and one more simple modification maybe needed with the Host: header depending if it reads port from the command line.
Tks.

**Comment by manuelbua** [comment]
Since i need to ensure the `Connection: close` header is present in the request header, this is what i'm using now (since i constantly keep getting the "too many open files" error even by tweaking limits by `ulimit`):
```bash
cat mydata | zgrab -port 80 -data <(echo -en "GET / HTTP/1.1\r\nHost: %d\r\nConnection: close\r\nUser-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36\r\n\r\n")
```

If that does what you need i'll be happy to provide a BTC address :yum:
