### ISSUE TITLE
installation error: go/src/github.com/zmap/zcrypto/ct/x509/root_darwin.go:73

### ISSUE THREAD

**Issue by seguri** [zmap/zgrab#308]
I can't install zgrab:

```
$ export GOPATH=$(go env GOPATH)
$ go get github.com/zmap/zgrab
# github.com/zmap/zcrypto/ct/x509
../zcrypto/ct/x509/root_darwin.go:73: cannot use nil as type _Ctype_CFDataRef in assignment
$ echo $?
2
```

**Comment by seguri** [comment]
Why was this closed?

**Comment by didierhk** [comment]
@seguri 

Please find workaround on https://github.com/zmap/zcrypto/issues/121

For your persual,

As a workaround, build with Go 1.9:

$ brew install go@1.9
$ /usr/local/opt/go@1.9/bin/go get -u github.com/zmap/zgrab

**Comment by syclops** [comment]
@seguri 

For what it's worth, I ran into this problem as well. It's possible to build this with Go 1.10 by running
```
go tool fix -r cftype $GOPATH/src/github.com/zmap/zgrab
go tool fix -r jni $GOPATH/src/github.com/zmap/zgrab
```
(There are only two offending lines anyway. You could just manually change `nil` to `0` in `$GOPATH/src/github.com/zmap/zgrab/vendor/github.com/zmap/zcrypto/ct/x509/root_darwin.go`, line 73 and in `$GOPATH/src/github.com/zmap/zgrab/vendor/github.com/zmap/zcrypto/x509/root_cgo_darwin.go`, line 100.)
