### ISSUE TITLE
Custom banner grab output data

### ISSUE THREAD

**Issue by Sesaru2** [zmap/zgrab#313]
Hello, I would like to know how to obtain specific output data of zgrab. For example I just want to get the Server, WWW-Authenticate and Content-Type data. Only that information and nothing else. I hope you can help me and in advance thank you very much

**Comment by zakird** [comment]
You can filter this data out using a post processor such as `jq` (https://stedolan.github.io/jq/). We do not plan to allow user configurable output when a large number of (much better tools) exist to do his.
