### ISSUE TITLE
Running without error but getting no output

### ISSUE THREAD

**Issue by meganhmoore** [zmap/zgrab#317]
I have a remote server that I am trying to run a zgrab scan from. 
I have been trying this: 
sudo zmap -p 8081 -i bond1 -v 5 -G "xx:xx:xx:xx:xx:xx" -S xx.xxx.xxx.xxx --vpn -B 10M -n 100000 --output-fields=* | ./zgrab -port 8081 -http="/" --output-file=test1.json

it runs zmap without error but has no result, and when it goes on to zgrab some of the time I get:
 [ERROR] log: Invalid IP address saddr. 

Otherwise I get no error message at I all.

I have specified the gateway using a bunch of different options from ifconfig to see if any of them work, and I have tried specifying with a bunch of other flags, but this is the configuration that gets the farthest without error. What am I doing wrong?

**Comment by zakird** [comment]
This issue doesn't look related to ZGrab, but rather ZMap. The reason you're getting this error in ZGrab is that you're passing in the string "saddr" because it's a header in the CSV output of ZMap because of  `--output-fields=*`. It's expecting IPs no a CSV file.
