### ISSUE TITLE
zgrab json.go errors

### ISSUE THREAD

**Issue by zerstoeren** [zmap/zgrab#35]
Hey guys.  Love the software... I run go get github.com/zmap/zgrab and get the following errors on json.go.  I have tested on 1.3.3, 1.4.1 and 1.4.2 and received the same errors on all three.  

go get github.com/zmap/zgrab
github.com/zmap/zgrab/ztools/x509/pkix
/home/ubuntu/go/src/github.com/zmap/zgrab/ztools/x509/pkix/json.go:53:13: error: reference to undefined field or method ‘String’
   enc[a.Type.String()] = a.Value
             ^
/home/ubuntu/go/src/github.com/zmap/zgrab/ztools/x509/pkix/json.go:65:19: error: reference to undefined field or method ‘String’
  enc.Type = a.Type.String()
                   ^
/home/ubuntu/go/src/github.com/zmap/zgrab/ztools/x509/pkix/json.go:78:17: error: reference to undefined field or method ‘String’
   Id:       e.Id.String(),

**Comment by dadrian** [comment]
Can you try clearing your `$GOPATH/bin` folder, and rerunning go get, using go 1.4 or higher?

**Comment by zerstoeren** [comment]
I did a fresh ubuntu install on a vm, did not set a $GOPATH/bin, install go1.4.2, but still getting the same errors.

**Comment by dadrian** [comment]
To build the software you need to set a `$GOPATH`. There are directions linked in the README.

**Comment by zerstoeren** [comment]
I got it working.  For whatever reason, it didn't care for the gopath that I was trying to set originally.

**Comment by stackoverflowin** [comment]
Getting the same error:

root@a:~# export GOPATH=$HOME/bin
root@a:~# go get github.com/zmap/zgrab
# github.com/zmap/zgrab/ztools/x509/pkix
bin/src/github.com/zmap/zgrab/ztools/x509/pkix/json.go:53:13: error: reference to undefined field or method ‘String’
   enc[a.Type.String()] = a.Value

**Comment by dadrian** [comment]
You likely need to update your go compiler to be at least version 1.5
