### ISSUE TITLE
using domain names with zgrab and sip banners

### ISSUE THREAD

**Issue by zerstoeren** [zmap/zgrab#37]
Can you provide an example of how we can use domain names with zgrab?

I see it has http-req-domain, but when I try to pass a domain name it doesn't seem to work.

Also, can zgrab pull sip banners?

**Comment by dadrian** [comment]
Given a file of the form:

```
1.2.3.4,domain.com
2.3.4.5,website.com
```
run `cat domains.csv | zgrab --port 80 --data http-req-domain`

ZGrab still requires you to manually look up the domain name. The `http-req-domain` file simply allows you to set the `Host: <domain>` header in an HTTP request.

As for SIP banners, if I'm not mistaken that's a UDP protocol. I think ZMap might be able to scan for that directly, check the ZMap UDP probes.

**Comment by zerstoeren** [comment]
Thanks dadrian.  i actually changed the command to zgrab --input-file=domains.csv --port=80 --data http-req-domain --output-file=output.json

i'm still not getting sip banners, but working on it.  sip looks to be on TCP 5060 though.
