### ISSUE TITLE
Fix test suite

### ISSUE THREAD

**Issue by corny** [zmap/zgrab#45]
I corrected the imports and created a configuration for Travis CI. There are still some failing tests in my branch: https://github.com/zmap/zgrab/compare/master...corny:travis
https://travis-ci.org/corny/zgrab

**Comment by dadrian** [comment]
I fixed the tests for ztls and commented out old tests that checked unimplemented / changed functionality. The build now passes on Travis.

Future work includes fixing up the tests for ZGrab itself, and finishing implementing JSON decode.

**Comment by corny** [comment]
great work! :+1:
