### ISSUE TITLE
'go get github.com/zmap/zgrab' on CentOS

### ISSUE THREAD

**Issue by svshearer** [zmap/zgrab#49]
I am using CentOS and ran the following command:

go get github.com/zmap/zgrab

The output from the command is:

'# github.com/zmap/zgrab/ztools/x509
root/go/src/github.com/zmap/zgrab/ztools/x509/x509.go:364: undefined: elliptic.P224
root/go/src/github.com/zmap/zgrab/ztools/x509/x509.go:377: undefined: elliptic.P224
root/go/src/github.com/zmap/zgrab/ztools/x509/x509.go:1436: undefined: elliptic.P224

It looks like the issue is because  error is because "golang in RHEL/CentOS does not support Elliptic Curve cryptography (because it's patented) and it's specifically removed from CentOS/RHEL."

Is there a suggested work around?

Thanks,
Spencer

**Comment by dadrian** [comment]
Have you tried installing Go from https://golang.org/dl/?

**Comment by svshearer** [comment]
That took care of the problem. Thanks very much.
