### ISSUE TITLE
Check for safe primes

### ISSUE THREAD

**Issue by dadrian** [zmap/zgrab#55]

**Comment by zakird** [comment]
also add "check if prime is even prime"

**Comment by dadrian** [comment]
After consulting with cryptographers, it looks like the thing to do is implement the tests described by DJB on page 2 of http://cr.yp.to/papers/sigs.pdf. This becomes a whole lot easier in Golang 1.5, which should contain a native implementation for calculating the Jacobi symbol of two *big.Int objects, so we'll wait for that to be released.

**Comment by zakird** [comment]
Offhand, I believe this is out of scope of ZGrab and should be a separate utility. Thoughts on closing @dadrian?
