### ISSUE TITLE
Fully implement ECDHE ciphers

### ISSUE THREAD

**Issue by dadrian** [zmap/zgrab#56]

**Comment by corny** [comment]
Do you mean just capturing the ECDHE parameters?

I have already implemented this:
https://github.com/corny/zgrab/commit/230089b13b474e9e0c5df596a9f6e75d9f1e629f

**Comment by dadrian** [comment]
That's part of it (and I'll probably merge it soon), but I was referring to wider set of all/most ciphers that use ECDHE and aren't currently implemented in the Golang TLS library.
