### ISSUE TITLE
Add support for DH and ECDH fixed-parameter ciphers

### ISSUE THREAD

**Issue by dadrian** [zmap/zgrab#62]
This requires updating the X.509 library for fixed-paramters (see https://tools.ietf.org/html/rfc3279#section-2.3.5), and adding the relevant cipher suites.

**Comment by zakird** [comment]
@dadrian do you actually plan on implementing this or this a wish list item? I'm assigning to functionality wish list for now.

**Comment by dadrian** [comment]
Wish list sounds reasonable; this was originally an issue because of Safari, however Safari has since pulled support for these ciphers in the wake of the KCI paper at WOOT 15.

**Comment by zakird** [comment]
IF that's the case, I'd say let's just close this. The reality is that we're never going to implement it.
