### ISSUE TITLE
Add Port in output  

### ISSUE THREAD

**Issue by qingxp9** [zmap/zgrab#64]
when i analyze the output file,it can't show which port does it return from.
So I hope to add the port information in output

And it's convenient if support multiport set.

**Comment by zakird** [comment]
This can be output by setting which fields you want with --output-fields. However, given that you're scanning a single port, they're all just going to say that one port.

**Comment by zakird** [comment]
Whoops, thought this was on different project. Please ignore last comment if you received notification.

**Comment by qingxp9** [comment]
@zakird  
I mean when i execute

    zmap -p 80 -w url.txt -o - | zgrab --port 80 --data=http-req >> test.txt

I hope the the output JSON every line have the "port" item rather than output it at last line .
If this,i could output different port scan information  in one file

**Comment by dadrian** [comment]
This is output by ZGrab2. https://github.com/zmap/zgrab2
