### ISSUE TITLE
Not collecting entire FTP banner

### ISSUE THREAD

**Issue by aaspring** [zmap/zgrab#68]
In some cases, ZGrab does not collect the entire FTP banner. For instance, the IP 92.87.126.99.

ZGrab gives the banner ``220-National Instruments FTP''

The actual banner is ``220-National Instruments FTP\r\n220 Service Ready''

**Comment by aaspring** [comment]
Caused by running with the the '--port=21 --banners' flags and not the '--ftp' flag (pull request #70 alters to '--ftp-banners').

Running with correct flags may require modification of ztag IOT use updated JSON format.

**Comment by zakird** [comment]
What's the status of this? Did the recent pull requests fix this?

**Comment by aaspring** [comment]
Were 2 problems with this.

The first is that the regex to check completion was incorrect. This is fixed in PR #70.

The second is that the scans were running with the "--banners" flag and not the "--ftp" flag, so if the banner was sent in multiple packets, it wasn't guaranteed to wait for the entire banner before reading and closing the connection. This is not fixable via Github and requires alteration to automatic scans.

@dadrian and I have been talking about how this may affect the annotations b/c of output, currently undecided as to how/if patching the annotations can be fixed.

**Comment by zakird** [comment]
@aaspring is this resolved, or what's going on?

**Comment by zakird** [comment]
I believe that this is resolved by ZGrab2 having an easily identifiable FTP module. Closing out.
