### ISSUE TITLE
Start documentation

### ISSUE THREAD

**Issue by zakird** [zmap/zgrab#78]

**Comment by jordan-wright** [comment]
Is there documentation on the architecture of zgrab anywhere? I'd like to add handlers for other services (such as elasticsearch, cassandra, redis, etc.), but don't know where to start. All the service parsing seems to be intermingled so I'm not sure where a defined starting point would be.

Happy to help get these knocked out, but I would appreciate some pointers to the right places to start 😄 

Keep up the great work!

**Comment by dadrian** [comment]
We're hopefully reworking the structure of ZGrab to be much easier to use over the next month or so. The current process is a bit of a mess. Did you have a specific feature you wanted to implement?

As for output, it usually works best to just pipe ZGrab into something that consumes JSON, rather than add a new output type.

**Comment by jordan-wright** [comment]
Good question. My goal is to get these protocols in the censys data. I think the only thing keeping censys from being fully on-par with things like Shodan is support for other protocols. I think the zmap data is more accurate than others, but the lack of protocol support keeps me from being able to use it for different projects.

I'm a huge fan of censys, so I'm more than happy to put the legwork in to make this happen. I could just use some help figuring out where to assist.

**Comment by zakird** [comment]
While the structure is going to change, the meat of ZGrab isn't. We're
still going to be used golang etc. If you're willing to help out, I'd say
start out just by writing the go code that tackles the connection for each
of these protocols (e.g., given an IP and a port) and then returns a struct
about how the service is configured. We can continue to work on cleaning up
the framework and then integrating the two halves once they're complete.

Zakir

**Comment by zakird** [comment]
This has been addressed in the ZGrab2 framework, which is superseding this project. Closing.
