### ISSUE TITLE
all json serializers need matching deserializers

### ISSUE THREAD

**Issue by zakird** [zmap/zgrab#81]
This allows someone to easily deal with the data later in golang

**Comment by jordan-wright** [comment]
I actually had a question about this - I noticed that [summary](https://github.com/zmap/zgrab/blob/master/summary.go) has its ```encodedSummary``` equivalent that appears to only give the benefit of turning "" into null when encoded.

Does this provide real benefit? I personally don't see the issue with empty strings, as it doesn't seem necessarily incorrect.

**Comment by dadrian** [comment]
There's a lot of decisions made in ZGrab when we were first writing it that were just plain wrong. Partially, just because we were wrong, and partially due to not knowing Go very well when I first wrote it.

In situations like this, the probably correct thing to do is set the field to `omitempty`.
