### ISSUE TITLE
Get Garbled when website's charset is gb2312

### ISSUE THREAD

**Issue by qingxp9** [zmap/zgrab#85]
i get this output

> {"ip":"xxxxxx","timestamp":"2015-11-10T18:30:44+08:00","data":{"read":"HTTP/1.1 200 OK\r\nDate: Tue, 10 Nov 2015 10:30:45 GMT\r\nServer: Apache\r\nX-Powered-By: PHP/5.2.17p1\r\nContent-Length: 5541\r\nConnection: close\r\nContent-Type: text/html\r\n\r\n\n\u003c!DOCTYPE html\u003e\r\n\u003chtml\u003e\r\n        \u003chead\u003e\r\n        \u003cmeta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\" /\u003e\r\n        \u003cmeta name=\"Keywords\" content=\"360\ufffd\ufffd\ufffdε㿨\ufffd\ufffdֵ\" /\u003e\r\n        \u003cmeta name=\"Description\" content=\"360\ufffd\ufffd\ufffdε㿨\ufffd\ufffdֵ\" /\u003e\r\n        \u003ctitle\u003eBitdefender\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd","write":"GET / HTTP/1.1\nHost: 10.142.106.14\n\n"}}

How could i do to convert gb2312 ?

**Comment by zakird** [comment]
Your best currently would be to convert this post facto, using Python or another other language of your choice. I don't think that we'll want to output files in anything under than utf-8 for the time being and it doesn't seem like a good idea to change the encoding of individual records.

**Comment by dadrian** [comment]
Unfortunately, I think we lose a lot of the data that would be required to recreate this post facto, since Golang will replace any byte sequence that's not valid UTF-8 with the Unicode replacement character. We might be able to detect other encoding and reencode them to UTF-8 before outputting?

**Comment by qingxp9** [comment]
Is there a general solution for non-utf8 encoding?

**Comment by dadrian** [comment]
I'm not sure. I need to look into this from both a Golang and JSON perspective.

**Comment by dadrian** [comment]
We've moved development to ZGrab2, which has some related issues: https://github.com/zmap/zgrab2/issues/197
