### ISSUE TITLE
Support TLS Extended Master Secret extension (RFC 7627)

### ISSUE THREAD

**Issue by dadrian** [zmap/zgrab#89]
This is now supported in Chrome and NSS.

https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/NSS_3.21_release_notes
https://tools.ietf.org/html/rfc7627

**Comment by aaspring** [comment]
Support added in PR #108, commit f4cc6d29f0b054207a118413f2ff9e99f8dd90df

**Comment by zakird** [comment]
Closing per Drew's commit that implements this.
