### ISSUE TITLE
go get: undefined: elliptic.P224

### ISSUE THREAD

**Issue by d33tah** [zmap/zgrab#97]
```
$ go get github.com/zmap/zgrab
# github.com/zmap/zgrab/ztools/x509
GOPATH/src/github.com/zmap/zgrab/ztools/x509/x509.go:364: undefined: elliptic.P224
GOPATH/src/github.com/zmap/zgrab/ztools/x509/x509.go:377: undefined: elliptic.P224
GOPATH/src/github.com/zmap/zgrab/ztools/x509/x509.go:1434: undefined: elliptic.P224
```

**Comment by d33tah** [comment]
Apparently this was because Fedora didn't ship with a proper build of Go. Fixed by downloading and installing one from golang.org.

**Comment by dadrian** [comment]
For future reference, pretty much every Linux distro ships with an old version of Golang

:(

**Comment by ljdelight** [comment]
This is not from using an old version go. Fedora Fedora 24 package is golang-1.6.2 (the latest version) and does not include P224. Fedora users must use the golang package from github.
