### ISSUE TITLE
zmap build issues when updating to new version

### ISSUE THREAD

**Issue by zerstoeren** [zmap/zgrab#99]
Hey Guys... I'm getting build issues when trying to build the new version of zmap.

I run cmake -DENABLE_DEVELOPMENT=OFF successfully, but when I run make, I get:

Scanning dependencies of target zblacklist
[  1%] Building C object CMakeFiles/zblacklist.dir/zblacklist.o
[  2%] Building C object CMakeFiles/zblacklist.dir/zbopt_compat.o
Linking C executable zblacklist
/usr/bin/ld: cannot find -lzmaplib
collect2: error: ld returned 1 exit status
make[2]: *** [zblacklist] Error 1
make[1]: *** [CMakeFiles/zblacklist.dir/all] Error 2
make: *** [all] Error 2

is anyone else having this problem?

**Comment by dadrian** [comment]
Are you passing the path to the root of the repository to CMake, and not the src/ folder?

**Comment by zerstoeren** [comment]
I just realized that I put a zmap question in the zgrab repo.  My bad.  I was in src.  When I try from zmap root, I get this error:

[ 11%] Built target zmaplib
Scanning dependencies of target zblacklist
[ 12%] Building C object src/CMakeFiles/zblacklist.dir/zblacklist.c.o
[ 13%] Building C object src/CMakeFiles/zblacklist.dir/zbopt_compat.c.o
Linking C executable zblacklist
[ 15%] Built target zblacklist
Scanning dependencies of target zmap
[ 16%] Building C object src/CMakeFiles/zmap.dir/aesrand.c.o
[ 17%] Building C object src/CMakeFiles/zmap.dir/cyclic.c.o
[ 18%] Building C object src/CMakeFiles/zmap.dir/expression.c.o
[ 19%] Building C object src/CMakeFiles/zmap.dir/fieldset.c.o
/root/zmap/src/fieldset.c:15:20: fatal error: unistr.h: No such file or directory
 #include <unistr.h>
                    ^
compilation terminated.
make[2]: *** [src/CMakeFiles/zmap.dir/fieldset.c.o] Error 1
make[1]: *** [src/CMakeFiles/zmap.dir/all] Error 2
make: *** [all] Error 2
 Is there another dependency that I'm missing maybe?

**Comment by zerstoeren** [comment]
I got it.  for ubuntu/debian, you also have to install libunistring-dev

**Comment by dadrian** [comment]
Yup. This is a more recent dependency, although I believe we added it to INSTALL.md.

**Comment by zerstoeren** [comment]
i should have read that.  i was following the website instructions.  :)  Thanks @dadrian.

**Comment by chaozai1028l** [comment]
[ 23%] Building C object src/CMakeFiles/zmap.dir/fieldset.c.o
/data/ZMAP/zmap/src/fieldset.c:15:20: fatal error: unistr.h: No such file or directory
 #include <unistr.h>
                    ^
compilation terminated.
make[2]: *** [src/CMakeFiles/zmap.dir/fieldset.c.o] Error 1
make[1]: *** [src/CMakeFiles/zmap.dir/all] Error 2
make: *** [all] Error 2

are you have a answer for this question?
